server:
  port: 8081

spring:
  application:
    name: disk-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orodisk?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 111111
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      password: 111111
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  ai:
    zhipuai:
      api-key: 7c83900b6998f3b0416d68c3f83b1102.kajXU5bUNvKavRHR
      embedding:
        options:
          model: embedding-3
    vectorstore:
      qdrant:
        host: 127.0.0.1
        port: 6334
        collection-name: disk
        use-tls: false
        initialize-schema: true
  threads:
    virtual:
      enabled: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: top.orosirian.orodisk.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  is-read-header: true
  is-read-cookie: false

disk:
  storage:
    base-path: /opt/OroDisk/storage/
    temp-path: /opt/OroDisk/temp/
#    base-path: E:/stuff/OroDisk
#    temp-path: E:/stuff/OroDisk/temp
  quota:
    default-size: 104857600
  clean:
    cron: 0 0 3 * * ?
  share:
    base-url: http://www.orosirian.top/s/



